SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Dropping [dbo].[huxSP]'
GO
DROP PROCEDURE [dbo].[huxSP]
GO
PRINT N'Dropping [dbo].[StandardBankTable]'
GO
DROP TABLE [dbo].[StandardBankTable]
GO
PRINT N'Altering [dbo].[States]'
GO
ALTER TABLE [dbo].[States] DROP
COLUMN [Test]
GO

