SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Dropping [dbo].[Huxley]'
GO
DROP TABLE [dbo].[Huxley]
GO
PRINT N'Dropping [dbo].[huxSP]'
GO
DROP PROCEDURE [dbo].[huxSP]
GO
PRINT N'Altering [dbo].[Clients]'
GO
ALTER TABLE [dbo].[Clients] DROP
COLUMN [Twitter]
GO

