SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Creating [dbo].[OctoCredentials]'
GO
CREATE TABLE [dbo].[OctoCredentials]
(
[OctopusID] [nchar] (10) NULL,
[OctopusURL] [nchar] (10) NULL,
[OctopusAPI] [nchar] (10) NULL
)
GO

