SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Creating [dbo].[IDAddressBook]'
GO
CREATE TABLE [dbo].[IDAddressBook]
(
[FirstName] [nchar] (10) NULL,
[LastName] [nchar] (10) NULL,
[ID] [nchar] (10) NULL
)
GO

