SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Creating [dbo].[StandardBankTable]'
GO
CREATE TABLE [dbo].[StandardBankTable]
(
[ID] [int] NULL
)
GO
PRINT N'Creating [dbo].[huxSP]'
GO
--SET QUOTED_IDENTIFIER ON|OFF
--SET ANSI_NULLS ON|OFF
--GO
CREATE PROCEDURE [dbo].[huxSP]
    @parameter_name AS INT
-- WITH ENCRYPTION, RECOMPILE, EXECUTE AS CALLER|SELF|OWNER| 'user_name'
AS
BEGIN
    SELECT * FROM dbo.StandardBankTable
END
GO
PRINT N'Altering [dbo].[States]'
GO
ALTER TABLE [dbo].[States] ADD
[Test] [nchar] (10) NULL
GO

