SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Creating [dbo].[test_Kathi]'
GO
CREATE TABLE [dbo].[test_Kathi]
(
[Col1] [int] NULL,
[Col2] [varchar] (30) NULL
)
GO

